#!/bin/python3
# https://www.hackerrank.com/contests/target-codevita-4/challenges/arrays-ds/problem

import math
import os
import random
import re
import sys

# Complete the reverseArray function below.
def reverseArray(a):
    #Function reverseArray with an argument 'arr' as array of elements
    #Take a empty list 't'
    t=[]
    
    #store the length of array in a variable 'n'
    n=len(a)
    
    #Traverse all the elements of array in reverse order and store it in 't'
    for i in range(n):
        j=n-1-i                # taking the reverse index
        t.append(a[j])         # one by one add elements in 't' 
    return t                    # return the reverse array 't'

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    # take the input as number of elements in array
    arr_count = int(input())

    #take the input array from user
    arr = list(map(int, input().rstrip().split()))

    #call a function reverseArray with an argument 'arr' as array of elements
    res = reverseArray(arr)

    #Function will return an array/list 
    fptr.write(' '.join(map(str, res)))
    fptr.write('\n')

    fptr.close()

# https://www.hackerrank.com/contests/target-codevita-4/challenges/arrays-ds/problem
